### PR TITLE
Fix timestamp precision bug

### PR DESCRIPTION
**Pull request by mwodahl**
# PR Details
## Description

This PR switches the DateTimeFormatter.ISO_INSTANT formatter to an explicit formatter as the ISO_INSTANT formatter no longer produces the correct timestamp.

Please note that this PR includes changes from the udp-security-headers branch and will need this branch to be merged before this PR can be completed. 

## Motivation and Context

Previously, the ODE was generating data that did not have the correct timestamp precision and therefore affected query ability in MongoDB. This change updates the odeReceivedAt value to use the correct timestamp precision. 

## How Has This Been Tested?

These changes have been tested by running the ODE locally and observing the output data in the log offloaded files data path. 

## Types of changes

- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ X ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.

### CODE REVIEW

**Review by dmccoystephenson — COMMENTED** [review]
This looks good to me & the unit tests pass! I'm glad we're standardizing to the `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'` format.

Waiting to approve until #65 is merged into dev.

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
There are some merge conflicts to address

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me & the unit tests pass!

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Pull request merged**
