### PR TITLE
Update msgRepeatOptions value

### PR DESCRIPTION
**Pull request by mwodahl**
Updates the RsuMsgRepeatOptions value used by SnmpNTCIP1218Protocol.java to use the correct value of 00 instead of the previous incorrect value of C0. 

Additionally, updates SnmpSessionTest.java to reflect this change. 

These updates have been deployed in dev and were verified to correctly deposit TIMs onto RSUs using NTCIP1218.

### CODE REVIEW

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me & the unit tests are passing!

**Comment by dmccoystephenson** [comment]
Marking this as a draft for now to prevent it from being merged until the changes in https://github.com/CDOT-CV/jpo-ode/pull/61 have been pushed through to USDOT dev.

**Comment by dmccoystephenson** [comment]
The changes in #61 have been merged into USDOT dev via https://github.com/usdot-jpo-ode/jpo-ode/pull/535, so we should be good to push changes to CDOT dev without it affecting the release. I am removing the 'draft' designation from this PR.

**Review by payneBrandon — APPROVED** [review]
ltgm! Compiles and unit tests pass

**Review by drewjj — APPROVED** [review]
Nice, thanks for making this change

**Pull request merged**
