### PR TITLE
Update POM Version 4.0.0

### PR DESCRIPTION
**Pull request by drewjj**
# PR Details
## Description

Upgraded the POM version to the next major version due to the repository's backwards incompatibility for the next quarterly release.

## Related Issue

N/A

## Motivation and Context

This is required due to backwards incompatibility and the need for a new version number to trigger GitHub to build a new artifact for this repository.

## How Has This Been Tested?

N/A

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by Michael7371 — APPROVED** [review]

**Review by dmccoystephenson — CHANGES_REQUESTED** [review]
There are a couple of lingering references to version 3.0.0-SNAPSHOT in some scripts:
- jpo-ode-svcs/run.bat
- jpo-ode-svcs/run.sh

These should be updated to reference 4.0.0-SNAPSHOT.

**Comment by drewjj** [comment]
> There are a couple of lingering references to version 3.0.0-SNAPSHOT in some scripts:
> 
> * jpo-ode-svcs/run.bat
> * jpo-ode-svcs/run.sh
> 
> These should be updated to reference 4.0.0-SNAPSHOT.

Addressed

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Review by dmccoystephenson — APPROVED** [review]
Looks good to me & I was able to package the project successfully!

**Pull request merged**
