### PR TITLE
Corrected NTCIP1218 msgRepeatsOption value

### PR DESCRIPTION
**Pull request by dmccoystephenson**
# PR Details
### Problem
The SnmpNTCIP1218Protocol class is currently using 0x00 for the msg repeats options value, which is incorrect (for the context of deploying an unsigned TIM). It should be using 0x80.

### Solution
The value being used for the msg repeats options value in the SnmpNTCIP1218Protocol class has been changed to 0x80.

## Related Issue
No related GitHub issue.

## Motivation and Context
The SnmpNTCIP1218Protocol class should use the correct value for the msg repeats option value to ensure a successful deposit.

## How Has This Been Tested?
Depositing to an RSU has been verified to work with this change.

## Types of changes
- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:
- [x] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by drewjj — APPROVED** [review]
It is important to note that x00 isn't incorrect entirely. It is incorrect for the context of deploying an unsigned TIM.

**Comment by dmccoystephenson** [comment]
> It is important to note that x00 isn't incorrect entirely. It is incorrect for the context of deploying an unsigned TIM.

Will deploying a signed TIM using 0x80 work?

**Comment by drewjj** [comment]
> > It is important to note that x00 isn't incorrect entirely. It is incorrect for the context of deploying an unsigned TIM.
> 
> Will deploying a signed TIM using 0x80 work?

If it is deployed to an RSU to be broadcasted from a RSU it will not work. 0x80 tells the RSU to sign the message before broadcasting it. This will cause an already signed message to be doubly wrapped with a 1609.2 header.

In summary:
0x00 - Tells the RSU to broadcast the message without signing it or attaching a 1609.2 header to it.
0x80 - Tells the RSU to sign and attach a 1609.2 header before broadcasting the message.

0xC0 shouldn't be used ever because it achieves some weird hybrid of the two.

**Comment by drewjj** [comment]
> > > > It is important to note that x00 isn't incorrect entirely. It is incorrect for the context of deploying an unsigned TIM.
> > > 
> > > 
> > > Will deploying a signed TIM using 0x80 work?
> > 
> > 
> > If it is deployed to an RSU to be broadcasted from a RSU it will not work. 0x80 tells the RSU to sign the message before broadcasting it. This will cause an already signed message to be doubly wrapped with a 1609.2 header.
> > In summary: 0x00 - Tells the RSU to broadcast the message without signing it or attaching a 1609.2 header to it. 0x80 - Tells the RSU to sign and attach a 1609.2 header before broadcasting the message.
> > 0xC0 shouldn't be used ever because it achieves some weird hybrid of the two.
> 
> @drewjj do we need a way to configure this then, to allow a choice of whether to have the RSU sign or just forward?

Yeah, that would be ideal if we want the ODE to be flexible.

**Comment by dmccoystephenson** [comment]
Marking this as a draft for now until we modify the functionality to use 0x00 / 0x80 depending on context.

**Pull request closed without merging**
