### PR TITLE
Kafka Connect & MongoDB Database

### PR DESCRIPTION
**Pull request by Michael7371**
# PR Details
## Description

This PR includes an additional docker-compose file named: "docker-compose-mongo.yml" which stands up a MongoDB database with a kafka connect instance to sink topics specified in the ./jpo-s3-deposit/mongo-connector/connect_start.sh script.

This PR also makes a change to the new kafka instance to use a docker managed kafka volume rather than a bind mount docker volume. This improves the performance of kafka (especially for windows users) by keeping everything in the docker file system. This is also helpful as now the kafka data can be reset if you attach the `-v` tag when using `docker compose down -v` command.

## Related Issue

No related issue.

## Motivation and Context

The move to have this functionality in the core ODE environment comes from combining requirements from the [jpo-conflictmonitor](https://github.com/usdot-jpo-ode/jpo-conflictmonitor) and the [jpo-cvmanager](https://github.com/usdot-jpo-ode/jpo-cvmanager). When deploying in a local environment both of these will require kafka connect and a MongoDB instance to work from.

## How Has This Been Tested?

If you stand up the mongo environment with the command: `docker compose -f .\docker-compose-mongo.yml up -d`, the standard ODE environment will be stood up along with the Mongo and kafka connect container. There is also a MongoDB configuration container that provisions users for RBAC. Please make sure to update your `.env` file with the new MongoDB required environmental variables from the `sample.env`

## Types of changes

- [ x ] Defect fix (non-breaking change that fixes an issue)
- [ x ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ x ] I have added any new packages to the sonar-scanner.properties file
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Michael7371** [comment]
Requires this PR to be merged first: https://github.com/CDOT-CV/jpo-ode/pull/71

**Comment by drewjj** [comment]
Got a small conflict with the README

**Review by drewjj — APPROVED** [review]
Looks good!

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Pull request merged**
