### PR TITLE
Update TIM schema

### PR DESCRIPTION
**Pull request by drewjj**
# PR Details
## Description

This pull request updates the TIM schema to include all supported ODE fields. This maintains the ASN1 being an optional field.

## Related Issue

N/A

## Motivation and Context

The previous TIM schema was only partially supporting the possible ODE fields of a TIM. This caused TIMs that were perfectly acceptable to fail validation checks where schema validation was implemented.

## How Has This Been Tested?

This has been tested with live TIM data generated in the CDOT environment based off WZDx data.

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/bugfix/Pull_request_template/docs/contributing_guide.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by payneBrandon — APPROVED** [review]
lgtm!

**Comment by Michael7371** [comment]
@drewjj it looks like TMC generated TIM messages fail the schema check:
image

Here is the message that gets output on the `topic.OdeTimJson` topic from a TIM message created from the ODE's `/tim` POST REST endpoint:
```JSON
{
	"metadata": {
		"request": {
			"ode": {
				"verb": "POST",
				"version": "3"
			},
			"rsus": {
				"rsus": {
					"rsuTarget": "10.145.2.60",
					"rsuUsername": "rwUser",
					"snmpProtocol": "NTCIP1218",
					"rsuRetries": "3",
					"rsuTimeout": "5000",
					"rsuPassword": "*",
					"rsuIndex": "21"
				}
			},
			"snmp": {
				"mode": "1",
				"deliverystop": "2024-09-30T10:00:00.0Z",
				"rsuid": "83",
				"deliverystart": "2024-09-25T10:00:00.0Z",
				"enable": "1",
				"channel": "183",
				"msgid": "31",
				"interval": "1000",
				"status": "4"
			}
		},
		"recordGeneratedBy": "TMC",
		"schemaVersion": "7",
		"payloadType": "us.dot.its.jpo.ode.model.OdeTimPayload",
		"odePacketID": "8D442EF0020C6B1A01",
		"serialId": {
			"recordId": "0",
			"serialNumber": "26",
			"streamId": "af334b18-487d-489c-9dff-fcdc99d7c293",
			"bundleSize": "1",
			"bundleId": "26"
		},
		"sanitized": "false",
		"recordGeneratedAt": "2024-10-22T21:01:28.000Z",
		"maxDurationTime": "8640",
		"odeTimStartDateTime": "2024-10-22T21:01:28.000Z",
		"odeReceivedAt": "2024-10-22T21:01:28.056Z"
	},
	"payload": {
		"data": {
			"MessageFrame": {
				"messageId": "31",
				"value": {
					"TravelerInformation": {
						"timeStamp": "426061",
						"packetID": "8D442EF0020C6B1A01",
						"urlB": "null",
						"dataFrames": {
							"TravelerDataFrame": {
								"durationTime": "8640",
								"regions": {
									"GeographicalPath": {
										"closedPath": {
											"false": ""
										},
										"anchor": {
											"lat": "389565870",
											"long": "-771491972"
										},
										"name": "Snow Turner Q1",
										"laneWidth": "5000",
										"directionality": {
											"both": ""
										},
										"description": {
											"path": {
												"offset": {
													"ll": {
														"nodes": {
															"NodeLL": [
																{
																	"delta": {
																		"node-LL1": {
																			"lon": "-906",
																			"lat": "-227"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-7088",
																			"lat": "-1334"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-5907",
																			"lat": "-1186"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-6104",
																			"lat": "-1631"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-6695",
																			"lat": "-2076"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-5316",
																			"lat": "-2372"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-6301",
																			"lat": "-2817"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-4726",
																			"lat": "-2372"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-4529",
																			"lat": "-2965"
																		}
																	}
																},
																{
																	"delta": {
																		"node-LL2": {
																			"lon": "-4135",
																			"lat": "-2817"
																		}
																	}
																}
															]
														}
													}
												},
												"scale": "0"
											}
										},
										"id": {
											"id": "0",
											"region": "0"
										},
										"direction": "1111000011110000"
									}
								},
								"startYear": "2024",
								"notUsed2": "0",
								"msgId": {
									"roadSignID": {
										"viewAngle": "1111111111111111",
										"mutcdCode": {
											"warning": ""
										},
										"position": {
											"lat": "389565870",
											"long": "-771491972"
										}
									}
								},
								"notUsed3": "0",
								"notUsed1": "0",
								"priority": "5",
								"content": {
									"advisory": {
										"SEQUENCE": {
											"item": {
												"itis": "4868"
											}
										}
									}
								},
								"url": "null",
								"notUsed": "0",
								"frameType": {
									"advisory": ""
								},
								"startTime": "426061"
							}
						},
						"msgCnt": "2"
					}
				}
			}
		},
		"dataType": "TravelerInformation"
	}
}
```

**Review by Michael7371 — CHANGES_REQUESTED** [review]
Looks like we might need to open up the schema a bit to allow for TIM's created from the REST endpoint to pass validation

**Comment by drewjj** [comment]
> Are there any breaking changes that would require an update to the major version of the application?

Nothing breaking here. Just a schema update intended to represent what the ODE currently outputs.

**Comment by drewjj** [comment]
> Looks like we might need to open up the schema a bit to allow for TIM's created from the REST endpoint to pass validation

I am told this may not be a factor anymore for the topics we intend for this to represent.

**Review by Michael7371 — APPROVED** [review]
Looks good!

**Review by dmccoystephenson — APPROVED** [review]
Looks good!

**Pull request merged**
